name: Build

on:
  push:
    branches:
      - main


jobs:
  sonar:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - "9000:9000"
    steps:
      - name: Wait for SonarQube to start
        run: |
          until curl -s http://127.0.0.1:9000/api/system/status | grep '"status":"UP"'; do
            echo "Waiting for SonarQube..."
            sleep 5
          done
      - name: Run SonarScanner
        run: sonar-scanner -Dsonar.host.url=http://127.0.0.1:9000
